# Copyright (c) 2026 Michael Mucciardi
# SPDX-License-Identifier: SSPL-1.0
"""Abstract base class for error mitigation strategies.

Error mitigators operate in two phases:
  1. pre_process: Generate additional/modified circuits needed for mitigation
     (e.g., noise-scaled circuits for ZNE, twirled variants for gate twirling)
  2. post_process: Apply correction to raw backend results
     (e.g., extrapolate to zero noise, correct readout errors)

The workflow calls pre_process before submitting to the backend, and
post_process after collecting results. For noiseless simulation,
error mitigation is skipped entirely.

To add a new error mitigation technique:
  1. Create a new .py file in plugins/error_mitigation/
  2. Subclass ErrorMitigator
  3. Implement pre_process() and post_process()
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from qiskit.circuit import QuantumCircuit

from lumi_hpc_qc.types import CircuitResult, ExperimentConfig


class ErrorMitigator(ABC):
    """Abstract error mitigation strategy."""

    name: str = ""
    requires_additional_circuits: bool = False  # ZNE/PEA=True, TREx=False

    @abstractmethod
    def pre_process(
        self,
        circuits: list[Any],
        config: ExperimentConfig,
    ) -> list[Any]:
        """Generate additional circuits needed for mitigation.

        Args:
            circuits: Original circuits to be executed.
            config: Experiment config for mitigation parameters.

        Returns:
            Expanded circuit list. May include the originals plus
            additional variants (noise-scaled, twirled, etc.).
            If no extra circuits are needed, returns input unchanged.

        Examples:
            ZNE: returns noise-scaled versions at multiple scale factors
            PEC: returns circuits with quasi-probability operations
            Gate twirling: returns twirled circuit variants
            TREx: returns original circuits + calibration circuits
        """

    @abstractmethod
    def post_process(
        self,
        results: list[CircuitResult],
        config: ExperimentConfig,
    ) -> list[CircuitResult]:
        """Apply mitigation to raw backend results.

        Args:
            results: Raw results from backend execution (may include
                results from additional circuits generated by pre_process).
            config: Experiment config for mitigation parameters.

        Returns:
            Corrected results in the same CircuitResult format.
            The number of returned results matches the number of
            original circuits (not the expanded set).

        Examples:
            ZNE: fits noise-scaled results, extrapolates to zero noise
            TREx: applies truncated readout error correction matrix
            PEC: combines quasi-probability samples
        """
